version: "3.9"

services:
  web:
    image: django
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    working_dir: /code/covidgeo
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/code:Z"
      - "./data:/data:Z"
    restart: always
    environment:
      - DEBUG=True
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=covidgeo123
    ports:
      - "8000:8000"
    depends_on:
      - "db"

  celery:
    image: django
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    working_dir: /code/covidgeo
    command: celery -A covidgeo worker --loglevel=INFO
    volumes:
      - ".:/code:Z"
      - "./data:/data:Z"
    restart: always
    environment:
      - DEBUG=False
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=covidgeo123
    depends_on:
      - "db"
      - "redis"

  redis:
    image: redis:alpine3.14
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgis/postgis:13-3.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    user: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: covidgeo123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: {}
